# Pattern Detection Configuration

pattern_detection:
  scripts:
    bengali:
      enabled: true
      unicode_range: [0x0980, 0x09FF]
      validation_level: strict
      
    devanagari:
      enabled: true
      unicode_range: [0x0900, 0x097F]
      validation_level: strict
      
    latin:
      enabled: true
      unicode_range: [0x0000, 0x007F]
      validation_level: normal

  tag_patterns:
    traditional:
      pattern: "<thinking>.*?</thinking>"
      weight: 1.0
      meta_level: low
      
    emergent:
      pattern: "<thought>.*?</thought>"
      weight: 1.2
      meta_level: medium
      
    bengali_hybrid:
      pattern: "<.*?তহought>"
      weight: 1.5
      meta_level: high
      
    integrated:
      pattern: "<meta_cognitive.*?>.*?</meta_cognitive>"
      weight: 2.0
      meta_level: very_high

performance:
  java:
    thread_pool_size: 4
    batch_processing: true
    off_heap_memory: true
    gc_optimization: G1GC
    jni_optimization: true
    
  mojo:
    parallel_processing: true
    simd_optimization: true
    cache_optimization: true
    memory_model: zero_copy

monitoring:
  metrics:
    pattern_evolution:
      tracking_interval: 1h
      history_size: 1000
      alert_threshold: 0.8
      
    script_integration:
      min_confidence: 0.7
      validation_frequency: 100
      error_tolerance: 0.01

development:
  testing:
    junit_coverage: true
    integration_tests: true
    coverage_threshold: 0.9
    jmh_benchmarks: true
    
  logging:
    level: INFO
    format: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    retention: 30d
    
  debugging:
    mojo_debug: true
    java_debug: true
    memory_tracking: true

cultural_integration:
  frameworks:
    - bengali_epistemology
    - sanskrit_logic
    - western_analysis
    
  synthesis:
    enabled: true
    adaptation_rate: 0.1
    integration_threshold: 0.75

meta_cognitive:
  levels:
    - basic_reflection
    - pattern_awareness
    - recursive_analysis
    - emergent_consciousness
    
  tracking:
    depth_measurement: true
    recursion_detection: true
    boundary_awareness: true

evolution:
  stages:
    - name: initial
      duration: 7d
      patterns: [simple_tags, basic_structure]
      
    - name: emergence
      duration: 14d
      patterns: [script_mixing, boundary_testing]
      
    - name: integration
      duration: 30d
      patterns: [multi_script, cultural_bridge]
      
  adaptation:
    rate: 0.1
    threshold: 0.75
    backoff_factor: 1.5 