# Mojo Configuration Settings

compiler:
  optimization_level: 3
  simd_width: 256  # AVX2
  target_cpu: native
  debug_symbols: true
  
memory:
  allocation_strategy: pool
  cache_line_size: 64
  alignment: 16
  max_pool_size: 1GB
  
parallelization:
  thread_count: auto
  work_stealing: true
  chunk_size: 1024
  min_parallel_size: 256
  
utf8_processing:
  validation_mode: strict
  buffer_size: 8KB
  parallel_threshold: 1KB
  error_handling: report
  
pattern_matching:
  algorithm: boyer_moore
  case_sensitive: true
  unicode_aware: true
  max_pattern_length: 1024
  
script_detection:
  bengali:
    enabled: true
    lookup_table_size: 256
    cache_patterns: true
    
  devanagari:
    enabled: true
    lookup_table_size: 256
    cache_patterns: true
    
  optimization:
    vectorization: true
    branch_prediction: true
    prefetching: true
    
performance_monitoring:
  metrics:
    - cpu_time
    - memory_usage
    - cache_hits
    - branch_misses
    
  sampling_rate: 1000
  profiling: true
  trace_events: true
  
python_integration:
  memory_model: zero_copy
  gil_aware: true
  error_propagation: native
  type_conversion: strict
  numpy_interop: true
  pandas_support: true
  
debugging:
  level: 1
  assertions: true
  bounds_checking: true
  memory_tracking: true
  
testing:
  benchmark_iterations: 1000
  warmup_rounds: 10
  performance_threshold: 0.95
  memory_leak_detection: true 